name: test_case_argos
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  dio: 4.0.4
  sizer: 2.0.15
  cached_network_image: ^3.2.0
  google_fonts:
  buttons_tabbar: ^1.3.2
  intro_slider: ^3.0.3
  intl: ^0.17.0

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
